import { Verb } from './verb';

/**
 * Model a query as a collection of serializble verbs.
 */
export default class Query {

  /**
   * Construct a new query instance.
   * @param {Verb[]} verbs An array of verb instances.
   * @param {object} params Optional query parameters, corresponding
   *  to parameter references in table expressions.
   */
  constructor(verbs, params) {
    this._verbs = verbs;
    this._params = params || null;
  }

  /**
   * Return the number of verbs in this query.
   */
  get length() {
    return this._verbs.length;
  }

  /**
   * Create new query instance from the given serialized object.
   * @param {object} object A serialized query representation, such as
   *  those generated by Query.toObject.
   * @returns {Query} The instantiated query.
   */
  static from({ verbs, params }) {
    return new Query(verbs.map(Verb.from), params);
  }

  /**
   * Evaluate this query against a given table and catalog.
   * @param {Table} table The Arquero table to process.
   * @param {Function} catalog A table lookup function that accepts a table
   *  name string as input and returns a corresponding Arquero table.
   * @returns {Table} The resulting Arquero table.
   */
  evaluate(table, catalog) {
    for (const verb of this._verbs) {
      table = verb.evaluate(table.params(this._params), catalog);
    }
    return table;
  }

  /**
   * Serialize this query as a JSON-compatible object. The resulting
   * object can be passed to Query.from to re-instantiate this query.
   * @returns {object} A JSON-compatible object representing this query.
   */
  toObject() {
    return {
      verbs: this._verbs.map(verb => verb.toObject()),
      ...(this._params ? { params: this._params } : null)
    };
  }

  /**
   * Serialize this query to a JSON-compatible abstract syntax tree.
   * All table expressions will be parsed and represented as AST instances
   * using a modified form of the Mozilla JavaScript AST format.
   * This method can be used to output parsed and serialized representations
   * to translate Arquero queries to alternative data processing platforms.
   * @returns {object} A JSON-compatible abstract syntax tree object.
   */
  toAST() {
    return {
      verbs: this._verbs.map(verb => verb.toAST()),
      ...(this._params ? { params: this._params } : null)
    };
  }
}